### ISSUE TITLE
Webui failed to start due to hostname error

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#202]
# Info

- Which version of Pi are you using: 3b+
- Which github revision of software: daynaport3
- Which board version: ??
- Which computer is the RaSCSI connected to: ??

# Describe the issue

User @takis_ reported this issue in Discord #rascsi-support when attempting to configure wifi using these steps: https://docs.google.com/document/d/1I4iFgQSYBCAi0xo9GqFOMDDFmt683b2TNaBw9j1fkb4/edit
The reported issue was that the webui was stuck in a loop of trying to start up but failing with errors in the system logs.
Including relevant excerpts from Discord conversations below.
```
===========================
pi@raspberrypi:~ $ rasctl -l
+----+----+------+-------------------------------------
| ID | UN | TYPE | DEVICE STATUS
+----+----+------+-------------------------------------
|  0 |  0 | SCHD | /home/pi/images/Macintosh_HD.hda
|  1 |  0 | SCDP | DaynaPort SCSI/Link
+----+----+------+-------------------------------------
pi@raspberrypi:~ $
```
but no webUI
I don't know if anything else works since the pi is not attached to the Mac now
and this is the output of ip addr show
```
pi@raspberrypi:~ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:3b:c7:57 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:6e:92:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.5/24 brd 192.168.2.255 scope global dynamic noprefixroute wlan0
       valid_lft 86254sec preferred_lft 75454sec
    inet6 fe80::ad10:4e8a:f8f3:d7e2/64 scope link
       valid_lft forever preferred_lft forever
4: rascsi_bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 32:7c:0d:11:b8:a3 brd ff:ff:ff:ff:ff:ff
    inet 10.10.20.1/24 brd 10.10.20.255 scope global rascsi_bridge
       valid_lft forever preferred_lft forever
    inet6 fe80::3086:89ff:fe15:b6e7/64 scope link
       valid_lft forever preferred_lft forever
5: ras0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master rascsi_bridge state UNKNOWN group default qlen 1000
    link/ether 32:7c:0d:11:b8:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::307c:dff:fe11:b8a3/64 scope link
       valid_lft forever preferred_lft forever

pi@raspberrypi:~ $ cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1               raspberrypi
```
takis_
 — 
08/14/2021
Let me post my complete log
```
Aug 15 00:51:16 raspberrypi systemd[1]: Started RaSCSI-Web service.
Aug 15 00:51:17 raspberrypi RASCSIWEB[932]: Starting web server...
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]: Traceback (most recent call last):
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "/usr/lib/python3.7/encodings/idna.py", line 165, in encode
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     raise UnicodeError("label empty or too long")
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]: UnicodeError: label empty or too long
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]: The above exception was the direct cause of the following exception:
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]: Traceback (most recent call last):
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "web.py", line 298, in <module>
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     serve(app, host="0.0.0.0", port=8080)
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "/home/pi/RASCSI/src/web/venv/lib/python3.7/site-packages/waitress/init.py", line 12, in serve
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     server = _server(app, **kw)
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "/home/pi/RASCSI/src/web/venv/lib/python3.7/site-packages/waitress/server.py", line 88, in create_server
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     sockinfo=sockinfo,
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "/home/pi/RASCSI/src/web/venv/lib/python3.7/site-packages/waitress/server.py", line 242, in init
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     self.server_name = self.get_server_name(self.effective_host)
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:   File "/home/pi/RASCSI/src/web/venv/lib/python3.7/site-packages/waitress/server.py", line 270, in get_server_name
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]:     server_name = self.socketmod.gethostbyaddr(server_name)[0]
Aug 15 00:51:19 raspberrypi RASCSIWEB[932]: UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Aug 15 00:51:19 raspberrypi systemd[1]: rascsi-web.service: Main process exited, code=exited, status=1/FAILURE
Aug 15 00:51:19 raspberrypi systemd[1]: rascsi-web.service: Failed with result 'exit-code'.
Aug 15 00:51:19 raspberrypi systemd[1]: rascsi-web.service: Service RestartSec=100ms expired, scheduling restart.
Aug 15 00:51:19 raspberrypi systemd[1]: rascsi-web.service: Scheduled restart job, restart counter is at 19.
```
can I somehow trace this "host" name somewhere you think?

takis_
 — 
08/14/2021
```
pi@raspberrypi:~ $ ping 0.0.0.0
PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.311 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.193 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.166 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.194 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.192 ms
^C
--- 0.0.0.0 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 163ms
rtt min/avg/max/mdev = 0.166/0.211/0.311/0.051 ms

pi@raspberrypi:~ $ hostname -I
192.168.2.5 10.10.20.1

Aug 15 01:17:16 raspberrypi avahi-daemon[355]: Withdrawing address record for 192.168.2.5 on wlan0.
Aug 15 01:17:16 raspberrypi avahi-daemon[355]: Host name conflict, retrying with raspberrypi-3
```
takis_
 — 
08/14/2021
To anyone interested: hulksmash's method works great. I simply needed to update my webUI because I had other raspberries in my home network all with the same names so maybe it got confused

**Comment by rdmark** [comment]
May be fixed with https://github.com/akuker/RASCSI/pull/209
